### ISSUE TITLE
Nested subgraphs with nodes cut off parent subgraph labels

### ISSUE THREAD

**Issue by rwbennett** [mermaid-js/mermaid#2345]
**Describe the bug**
When nesting subgraphs, the outer ones have their text cut off by the children they contain.

**To Reproduce**
See the following markup:
```
 graph LR
   subgraph A
        subgraph B
            C
        end
   end
```

**Expected behavior**
The label for "A" should not be obscured by B.

**Screenshots**
![image](https://user-images.githubusercontent.com/4762629/134742483-87fabfca-3959-46d8-ba46-a8e325c0d2e5.png)

**Comment by MikePreston** [comment]
bouncing this again. need a solution to this please!

**Comment by ankorstore-haddowg** [comment]
+1

**Comment by asafm** [comment]
I'm having the same issue. Can be seen clearly here: https://github.com/Opster/opensearch-k8s-operator/pull/50/files?short_path=69b1fce#diff-69b1fce49163aa67bbd8659f56a5ae9bb893bf732fbcc9971bdc1c5f24934b66

Screenshot: 
![image](https://user-images.githubusercontent.com/989425/156935154-4ac5bc68-fe98-46ad-8153-fcaf61ba134b.png)

Markdown:
```
  flowchart LR
       subgraph opensearch-operator-ns [OpenSearch Operator Namespace]
         direction BT
         service-monitor-controller[[ServiceMonitor CRD]]-- references -->opensearch-controller[/OpenSearch Controller/]
       end 
       subgraph opensearch-clusters
         subgraph opensearch-cluster-1 [OpenSearch Cluster 1 Namespace]
           direction BT
           subgraph ss1 [OpenSearch Nodes StatefulSets]
             subgraph node11 [OpenSearch Node]
               plugin11[Prometheus Exporter Plugin]    
             end
             subgraph node12 [OpenSearch Node]
               plugin12[Prometheus Exporter Plugin]    
             end
           end
           service-monitor-ss-1[[ServiceMonitor CRD]]-- references -->plugin11
           service-monitor-ss-1-- references -->plugin12
         end
         subgraph opensearch-cluster-2 [OpenSearch Cluster 2 Namespace]
           direction BT
           subgraph ss2 [OpenSearch Nodes StatefulSets]
             subgraph node21 [OpenSearch Node]
               plugin21[Prometheus Exporter Plugin]    
             end
             subgraph node22 [OpenSearch Node]
               plugin22[Prometheus Exporter Plugin]    
             end
           end
           service-monitor-ss-2[[ServiceMonitor CRD]]-- references -->plugin21
           service-monitor-ss-2-- references -->plugin22
         end
       end
       subgraph prometheus-operator-ns [Prometheus Operator Namespace]
         direction TB
         prometheus-controller[/Prometheus Controller/]
         alert-manager[/Alert Manager/]
         grafana[/Grafana/]-- Query -->prometheus[/Prometheus/]
         
         prometheus-. Node Discovery .->service-monitor-ss-1
         prometheus-. Node Discovery .->service-monitor-ss-2
         prometheus-- Read Metrics -->plugin11
       end
       opensearch-controller-. Deploys .->service-monitor-ss-1
```

**Comment by LuisBL** [comment]
having the same Pb, it is a bug worth prioritizing

**Comment by medliii** [comment]
Hello. I guess it was fixed.

![image](https://github.com/mermaid-js/mermaid/assets/1991105/2c5de431-302f-496c-9b55-f675190f3bf2)

![image](https://github.com/mermaid-js/mermaid/assets/1991105/26661fdd-81d2-4a81-b622-ba7b82469161)

**Comment by Saviq** [comment]
Still broken for multiline labels:
```
 graph LR
   subgraph A ["A 
   aaaaaaaaaaaaaaaaaaaa"]
        subgraph B
            C
        end
   end
```

<img width="830" height="659" alt="Image" src="https://github.com/user-attachments/assets/fb218ce1-f1f4-4c27-a178-fb7aecdecfa6" />
