### ISSUE TITLE
"Error: Diagram error not found." on await mermaid.mermaidAPI.render(id, text)

### ISSUE THREAD

**Issue by AlbinoGeek** [mermaid-js/mermaid#4140]
### Description

When I call the new async `mermaid.mermaidAPI.render` -- I get the error (see title).

### Steps to reproduce

1. Run code sample
2. Receive non-descript error

### Screenshots

![image](https://user-images.githubusercontent.com/1910461/221021755-6cc7d535-4c40-468c-ac77-6e15636cbc95.png)

### Code Sample

```ts
const mermaidConfig = {
  darkMode:  true,
  flowchart: {
    curve:       'basis',
    useMaxWidth: true,
  },
  fontFamily:    'Fira Code',
  maxTextSize:   1024 * 100,
  securityLevel: 'loose',
  startOnLoad:   true,
  theme,
  themeCSS,
}

const value = "graph TD\n\nHello --> World"

mermaid.mermaidAPI.initialize(mermaidConfig)

ref.current.removeAttribute('data-processed') // silly mermaid thinks it needs a DOM element
const svg = await mermaid.mermaidAPI.render(  // was mermaid.mermaidAPI.renderAsync
  'mermaid',
  value
)
ref.current.setAttribute('data-processed', 'true') // silly mermaid thinks it needs a DOM element

const buff = Buffer.from(svg.svg) // mermaid 10: svg -> svg.svg?
const base64data = buff.toString('base64')
setSvgData(base64data)
```

### Setup

**Desktop**

- OS and Version: Windows 10
- Browser and Version: Chrome, Edge, Firefox, Opera

### Additional Context

Non-descript error is non-descript.

**Comment by AlbinoGeek** [comment]
### Possibly Offending Files

https://github.com/mermaid-js/mermaid/blob/6b251de227d999af7371e4928445193fe3a6de54/packages/mermaid/src/diagram-api/diagramAPI.ts

https://github.com/mermaid-js/mermaid/blob/6b251de227d999af7371e4928445193fe3a6de54/packages/mermaid/src/Diagram.ts

**Comment by sidharthv96** [comment]
It's a concurrency bug when `  startOnLoad:   true,` is set. 
You can set that to `false` until the fix is released.

**Comment by sidharthv96** [comment]
```js
const { svg } = await mermaid.render( // mermaid 10: svg -> { svg }
  'mermaid',
  value
)
const buff = Buffer.from(svg) 
```

**Comment by AlbinoGeek** [comment]
@knsv This is not fixed.

It turns out you can actually cause this two ways:

1) With `startOnLoad: true` like you fixed.
2) With `startOnLoad: false`, but invalid syntax.

The second case is not fixed.

**Comment by shtratos** [comment]
@AlbinoGeek can you please share an example how it can be reproduced with `startOnLoad: false`?

 I suspect I'm running into this too in
https://github.com/mjbvz/vscode-markdown-mermaid/pull/177

**Comment by AlbinoGeek** [comment]
I don't quite know what changed, but it's all fixed now, can no longer reproduce!
