### ISSUE TITLE
Problem with rendering subgraphs in Flowchart / Graph

### ISSUE THREAD

**Issue by nirname** [mermaid-js/mermaid#4644]
# Description

This issue is a combination of

- #2429
- #2829
- #3981
- #4104
- #4201
- #4428
- #4508

Users face the same error when rendering flowchart / graph with subraphs.

# Problem

Problem is somewhere around

https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/dagre-wrapper/index.js#L72

That is the typical output they witness

```
mermaid-d39f8a39.js:11986 50.665 : ERROR :  Error parsing TypeError: Cannot read properties of undefined (reading 'id')
    at index-dda4cada.js:564:61
    at Array.map (<anonymous>)
    at recursiveRender (index-dda4cada.js:537:19)
    at index-dda4cada.js:551:25
    at Array.map (<anonymous>)
    at recursiveRender (index-dda4cada.js:537:19)
    at render (index-dda4cada.js:633:9)
    at Object.draw (styles-bc3c1782.js:397:9)
    at Object.render$1 [as render] (mermaid-d39f8a39.js:11720:25)
```

When a user enters one of the samples, he does not see output, or see "syntax error", although it is not syntax error at all.

![image](https://github.com/mermaid-js/mermaid/assets/2842432/2e5ab41d-8f29-4e68-96fd-4d227b897a15)

As we can see, it **renders** but it shows error because of `undefined` value during rendering, not parsing. It also means that our error message does not reflect the source of the problem.

# Failing examples

## Sample 1
```
graph TD;
subgraph A
  subgraph B
    C
  end
end
A --> D
B --> D
```
## Sample 2
```
flowchart TB
    subgraph A
        subgraph AA
            AA1
        end
    end
    subgraph B
        AB3
    end
    start --> A
    AA --> AB3
```
## Sample 3
```
graph TD;
subgraph A
  subgraph B
    C
  end
  E
end
A --> D
B --> D
%% Node to node
E --> D
```

## Sample 4
```
flowchart TD

sender-1 --> system --> receiver-1
sender-2 --> sub-system --> receiver-2

subgraph system
  subgraph sub-system
    service-1
    service-2
  end
end
```

## Sample 5

```
flowchart

  subgraph subgraph1
  end

  subgraph subgraph2
    subgraph subgraph201
       box1
    end
    subgraph subgraph202
       box2
    end
  end

  subgraph subgraph3
  end

  subgraph1 --> subgraph2
  subgraph201 --> subgraph3
  subgraph202 --> subgraph3
```

## Sample 6

```
flowchart LR

subgraph TOP
direction TB
subgraph B1
direction RL
i1 -->f1
end
subgraph B2
direction BT
i2 -->f2
end
end
A --> TOP --> B
B1 --> B2
C --> B1
```

**Comment by nirname** [comment]
@randolchance Absolutely, no one working on that issue right now. I can assign it to you

**Comment by randolchance** [comment]
**UPDATE 2023-08-04**

So far I've noticed a couple small oversights in the logic of the dagre-wrapper, specifically [here](https://github.com/mermaid-js/mermaid/blob/b87f1f209843ed794d83bfece5669adf595bdabd/packages/mermaid/src/dagre-wrapper/index.js#L52) and [here](https://github.com/mermaid-js/mermaid/blob/b87f1f209843ed794d83bfece5669adf595bdabd/packages/mermaid/src/dagre-wrapper/index.js#L115). Notice both the conditionals contain `node && node.clusterNode`, which forces the logic into the `else` statement when `node` is `undefined`, however the `else` statements both expect `node` to be defined regardless. Thus the check to see if `node` is defined is unnecessary and is in fact hiding the true issue: what is supposed to happen if a node is undefined? Are nodes ever supposed to be undefined? Until I better understand the larger picture, I cannot make any presumptions as to whether or not a node should always be defined.

Any insights or suggestions here are welcome.

**Comment by nirname** [comment]
Nodes and subgraphs are not supposed to be undefined in this diagram. However, dagre wrapper is not related to flowcharts only as far as I know. Try to investigate, perhaps those conditions were there to mitigate another issue. Try commenting out those condition and runing tests to see what will happen

**Comment by randolchance** [comment]
I believe commenting out the `node &&` part of the conditional `node && node.clusterNode` would only serve to error out on `node.clusterNode` when `node` is `undefined`.

I did, however, take your advice and look into wider issues that might be stemming from undefined nodes and found #3888 could be related. I also thought #3296 might be related, but reading the thread illuminated the solution to that issue, I believe. I commented there as such.

Still looking into this...

**Comment by randolchance** [comment]
**UPDATE 2023-08-19**

Looks as though the issue is somewhere in [dagre-d3](https://github.com/dagrejs/dagre-d3) which is not actively being maintained and they're basically saying they'd be happy if someone else took over lol.

I'll look further into this. Is there any kind of procedure in place for modifying a dependency into a custom version?

Also, I've been on vacation the past while, and I'm going on vacation again for a week as of tomorrow. I am very interested in working on this so please do not take my recent inactivity as indication of abandonment.

Thanks!

**Comment by SavvyShah** [comment]
## Reference sample
Below sample is quoted in the following sections.

```
graph TD;
  subgraph A
    subgraph B
      C
    end
  end
  A --> D
  B --> D
```
Subgraph A and B has selected C as the replacement node, which means edge (A --> D) to (C --> D) is converted due to some reasons.

## Notes

1. [`setEdge`](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/src/dagre-wrapper/mermaid-graphlib.js#L105) function adds node to a graph if not already existing.
2. The `setEdge` function call above inside the `copy` function should never be made if edge is not in cluster. For example, when the copy function is called with the subgraph of B, the edge (C --> D) which is going outside subgraph B shouldn't be allowed by [`edgeInCluster`](https://github.com/mermaid-js/mermaid/blob/b054766388e6ce926c01c913fc3100d4844a44fc/packages/mermaid/src/dagre-wrapper/mermaid-graphlib.js#L103) function. 

## Issue

As a result of the above, `setEdge` is called and it adds node `C` and node `D` to the subgraph of `B` but node `D` is not a part of subgraph `B`.

**Comment by akshayw1** [comment]
Hey,Is this issue still open, so that I can work on this.

**Comment by randolchance** [comment]
The problem likely lies in dagre, just a heads up. Available to discuss what I know.

**Comment by nirname** [comment]
@akshayw1 Of course, you can

**Comment by tedivm** [comment]
I will personally donate $75 to the person who fixes this bug, as I absolutely love this library but do not have the time to learn enough javascript to attempt a bug fix on my own.

**Comment by medliii** [comment]
Hello, I guess it was fixed
https://github.com/mermaid-js/mermaid/pull/5127

@nirname  try 10.8 version

**Comment by mathbraga** [comment]
Wow was unaware there were so many issues related to #5059, I fixed this with #5127, I tried all the samples here on current version 10.8 and all seem to be working. 

Sorry if someone else was working on this and I stepped on your toes, I had no idea about this chain of issues.

@medliii thanks for mentioning #5127 here

@tedivm keep your money it's all good 😅

**Comment by lrlunin** [comment]
Hello, I am still facing the issue with the example with both 10.8.0 and 10.9-rc1 versions.
```
flowchart LR

subgraph TOP
direction TB
subgraph B1
direction RL
i1 -->f1
end
subgraph B2
direction BT
i2 -->f2
end
end
A --> TOP --> B
B1 --> B2
C --> B1
```
I used files from https://cdnjs.com/libraries/mermaid/10.8.0 as an external library.

![image](https://github.com/mermaid-js/mermaid/assets/1849145/f09a8580-2b7a-4a8d-9ee7-096aa3241db7)
![image](https://github.com/mermaid-js/mermaid/assets/1849145/324fca51-cffe-4f5f-ab5b-58ff3df8a75c)

**Comment by lrlunin** [comment]
Hello there,

I was very happy to discover such great product as a mermaid and wanted to add this to xwiki we are using in our institute. The mermaid js will be added with a `requirejs` framework:
```js
require(["https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.8.0/mermaid.min.js"],
function(mermaid){mermaid.initialize({startOnLoad:true});});
```

Then very weird things happen. The graphs with nested subgraphs (!) **always** crash if I use a our website. The graphs without nested subgraphs **always** rendered properly. I use these two graphs as an example for nested and none subgraphs:
```html

{{velocity}}
{{html clean="false"}}
<div class="mermaid">
graph TD;
  subgraph A
  subgraph B
  C
  end
  end
  A --> D
  B --> D
</div>
{{/html}}
{{/velocity}}

{{velocity}}
{{html clean="false"}}
<div class="mermaid">
graph TD;
  subgraph A
  end
  A --> D
  B --> D
</div>
{{/html}}
{{/velocity}}
```
Remote website:
![image](https://github.com/mermaid-js/mermaid/assets/1849145/3fa648bd-8723-42c7-ab61-95934c741cf3)

However if I run the same setup on my localhost the nested subgraph example **almost always** (about 80%) displays correctly (but 20% times I have same syntax error) while the graph without nested subgraphs always rendered perfectly.
 
![image](https://github.com/mermaid-js/mermaid/assets/1849145/9a76a411-d5b1-4ed2-bf60-31a5b720178b)

But sometimes it also fails to render it. While there is no errors in console or whatever. It is really chaotic. If I refresh the page it can fail 5 times in a raw and then rendered appropriately. I emphasize that the non-nested-subgraphs charts are **always** rendered correctly. So I would like to ask if there is any possible race conditions appear? 
![image](https://github.com/mermaid-js/mermaid/assets/1849145/4f2c7277-0402-4d7b-b8c7-e385503e9850)
