### ISSUE TITLE
Changing the curve interpolation for flowchart doesn't do anything

### ISSUE THREAD

**Issue by 5FeetUnder** [mermaid-js/mermaid#6193]
### Description

Changing the curve type for a flowchart doesn't apply, no matter if it's changed in the config tab of the live editor, in the init directive or via `linkStyle`.

In the "next" live editor (which runs on an older version: `v11.0.0-alpha.6+7fec51f`) it still works as expected, in current and "develop" it doesn't.

### Steps to reproduce

1. open any mermaid flowchart
2. add any of the following (using `stepBefore` as example):
    * `%%{ init: { 'flowchart': { 'curve': 'stepBefore' } } }%%` at start of the mermaid block
    * `linkStyle default interpolate stepBefore;` inside the flowchart-definition
    * `"flowchart": { "curve": "stepBefore" }` in the config tab of the live editor
3. observe the flowchart not changing

### Develop Live Editor

with init directive:

![Image](https://github.com/user-attachments/assets/593cd3c2-529d-460c-aceb-e75e76b4c5df)

with `linkStyle`:

![Image](https://github.com/user-attachments/assets/a11bc44f-f859-48e1-967d-055dc7d6a1ec)

via config:

![Image](https://github.com/user-attachments/assets/df39b51b-02cc-4af1-9bbb-fdcf7c504089)

### "Next" Live Editor

with init directive:

![Image](https://github.com/user-attachments/assets/a74a1529-5941-4044-ae3c-db13591b5e30)

with `linkStyle`:

![Image](https://github.com/user-attachments/assets/75a677d2-9a4e-4ec5-b84d-4b65400fc385)

via config:

![Image](https://github.com/user-attachments/assets/71875277-ff33-4835-8a02-97561120aff1)

### Code Sample

```text
https://develop.git.mermaid.live/edit#pako:eNpVUM1ugzAMfhUrp02CF-AwacDWS6tNWk8DDhYYErXEkQmrKuDdF8rUbT75-3McT6rmhlSi2jNfao3i4ZiXFkI9F5kWM_gehwri-GnekYeeLV1nSB92DINm54ztHjd_upogm_arjcBrY0_LJmW3_JulGfJij86zq_4qxwvP8FKYdx3G_1e0UEi9Fi0mLcY1CmQolYpUT9KjacLq0xooldfUU6mS0DYop1JFG3__2apNgahH-foxDp5cSi1LwBCWXcJgHD1_XG2tEi8jRUp47LQKr5-HgEbXoKfcYCfY31mH9pP5F1NjPMthO-3twss32LN1xQ
```

### Setup

- Mermaid version: tested in v11.4.0 and the develop branch at v11.4.1+1d9c2aa
- Browser and Version: tested in Edge Version 131.0.2903.70 and Firefox Version 128.6.0esr

**Comment by closetgeekshow** [comment]
I'm also hitting my head against this issue, can't seem to find any workaround

**Comment by JonasCir** [comment]
Same here, I could not get the curve style to change anywhere, independently of the configuration method: JSON config in the online editor, directives, or config key in frontmatter. This feature is completely broken for me.

**Comment by krisho007** [comment]
Is there any Old or new version where this is fixed? OP talked about "Next". What it is? 
This bug definitely needs attention.

**Comment by softworkz** [comment]
It works in playground interestingly, which has version v11.4.1-b-14 but neither in Live editor nor in 11.4.1 nor 11.5.0

Why does it work in playground and how to get that version?

**Comment by FloatingGlimmersBreathingFlame** [comment]
Currently, it's March 20, 2025. I tested this phenomenon in version 11.5.0 and found it still persists. I then proceeded to test the following versions, and here are the corresponding results:
|version|is the problem exists|
|-|-|
|v 10.0.0|no|
|v 10.5.0|no|
|v 10.9.0|no|
|v 11.1.0|yes|
|v 11.3.0|yes|
|v 11.5.0|yes|
It appears that this issue exists in version 11 and above.Therefore, the latest usable version appears to be 10.9.0. A positive aspect is that this version supports KaTeX; however, it's worth noting that the extended node shapes feature was introduced in version 11.3, making this syntax unavailable in version 10.9.0. Additionally, certain link IDs that are parsable in version 11.5.0 (e.g.,  A e@--->B ) appear unprocessable in this version, despite not being documented as version-specific.

**Comment by softworkz** [comment]
@FloatingGlimmersBreathingFlame 

I can confirm this and I ran into the exaxt same issues unfortunately.

**Comment by softworkz** [comment]
> It works in playground interestingly, which has version v11.4.1-b-14 but neither in Live editor nor in 11.4.1 nor 11.5.0

It seems the reaction to my post was to disable the version display in the Playground - still works in the Live editor.


But it still can be seen:

![Image](https://github.com/user-attachments/assets/d7a8839f-fb46-4b6e-9cc9-a9104b720597)

Now try to hide that without breaking all workflow patterns... 😆
